In [2]:
import numpy as np
import pandas as pd

In [5]:
alltrails = pd.read_csv(r"C:\IT2\chatlyn\chatlyn-app\backend\src\datasets\alltrails_top50.csv")
alltrails.head()

,name,location,difficulty,length,elevation,reviews,rating,route_type
0,Angels Landing Trail,Zion National Park,Hard,6.9,557,24041,4.9,Out and Back
1,Navajo Loop and Queens Garden Trail,Bryce Canyon National Park,Moderate,5.0,198,15818,4.9,Loop
2,Devil's Bridge Trail,Coconino National Forest,Moderate,6.3,159,23938,4.7,Out and Back
3,Emerald Lake Trail,Rocky Mountain National Park,Moderate,5.1,214,14549,4.8,Out and Back
4,Vernal and Nevada Falls via Mist Trail,Yosemite National Park,Hard,10.3,673,12978,4.9,Loop

In [ ]:
alltrails.quantile([0.1, 0.9])

     length  elevation  reviews  rating
0.1    3.64      190.0   8227.1     4.7
0.5    7.65      446.5  10986.0     4.8